version: '3.9'
services:
  db:
    image: postgres:15.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: next-prisma
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
volumes:
  postgres:
